=== SamAxe/guard-puppy/protocoldb/protocoldb.dtd
<!-- A protocol database contains a sequence of protocol descriptions. The -->
<!-- lines attribute gives the number of lines in the xml source; it need  -->
<!-- not be accurate. -->
<!ELEMENT protocoldb (protocol)* >
<!ATTLIST protocoldb lines CDATA #IMPLIED>

<!-- A protocol element describes a single application-layer protocol, such -->
<!-- as the FTP file transfer protocol.  The name attribute gives a name -->
<!-- used by the firewall configuration script to refer to the protocol. -->
<!ELEMENT protocol
   (longname+, description*, classification, pragma*, network, security?,
   reference*) >
<!ATTLIST protocol name ID #REQUIRED>

<!-- A protocol's longname elements give reader-friendly names for display -->
<!-- in the GUI's protocol tree.  The lang attribute lets you give -->
<!-- different long names for different languages. -->
<!ELEMENT longname (#PCDATA) >
<!ATTLIST longname lang CDATA "en">

<!-- A protocol or message can have a more verbose description that the GUI -->
<!-- can display.  The lang attribute lets you give different descriptions -->
<!-- for different languages. -->
<!ELEMENT description (#PCDATA) >
<!ATTLIST description lang CDATA "en">

<!-- A protocol's classification is the node in the GUI's protocol tree -->
<!-- that the protocol should be displayed under. -->
<!ELEMENT classification EMPTY >
<!ATTLIST classification
    class (unknown | mail | chat | file | game | session | data | media | net)
        #REQUIRED >

<!-- Pragmas give extra information about elements.  Guarddog honors	-->
<!-- pragmas whose name attribute is "guarddog":			-->
<!-- * In a protocol element, the pragma's content is the name of a	-->
<!--   kernel module to load.						-->
<!-- * In a tcp, udp, icmp or ip element, a pragma with content RELATED -->
<!-- marks messages that will be handled automatically by iptables	-->
<!-- connection tracking.     -->      
<!ELEMENT pragma (#PCDATA) >
<!ATTLIST pragma name CDATA #IMPLIED>

<!-- The GUI can also display security-related information about a -->
<!-- protocol. -->
<!ELEMENT security EMPTY >
<!ATTLIST security
    threat   (unknown | low | medium | high) "unknown"
    falsepos (unknown | low | medium | high) "unknown">

<!-- A protocol's references give sources for further information about the -->
<!-- protocol, preferably with URIs.  Currently Guarddog ignores them.    -->
<!ELEMENT reference (#PCDATA) >
<!ATTLIST reference href CDATA #IMPLIED>

<!-- A protocol's network element defines the connections that the -->
<!-- (application layer) protocol might use.  A connection may use TCP, -->
<!-- UDP, ICMP, or some other IP (transport layer) protocol. -->
<!ELEMENT network (tcp | udp | icmp | ip)+ >
<!ATTLIST network>

<!-- An ip element defines a connection that uses an arbitrary IP	 -->
<!-- protocol.  The protocol attribute gives the protocol number; see    -->
<!-- /etc/protocols and http://www.iana.org/assignments/protocol-numbers -->
<!-- for lists. --> 
<!--   The source attribute states whether the connection is created by   -->
<!-- the client (the computer that used the application-layer protocol to -->
<!-- request a service) or the server.  The dest attribute does the same  -->
<!-- for the other computer. --> 
<!--   If direction is "both", data flows both ways through the connection. -->
<!ELEMENT ip (description | pragma)* >
<!ATTLIST ip
    protocol  CDATA		#REQUIRED
    source    (client | server) "client"
    dest      (client | server) "server"
    direction (both)		#IMPLIED>

<!-- Similarly, an icmp element defines a connection that uses the Internet -->
<!-- Control Message Protocol.  Instead of a protocol attribute, it -->
<!-- contains a type element, which gives the value of the ICMP message's -->
<!-- TYPE field, and of its CODE field if the message type uses codes. -->
<!ELEMENT icmp ((description | pragma)*, type, (description | pragma)*) >
<!ATTLIST icmp
    source (client | server) "client"
    dest   (client | server) "server">
<!ELEMENT type EMPTY>
<!-- value and code must be integers in 0..255. -->
<!ATTLIST type
    value CDATA #REQUIRED
    code  CDATA #IMPLIED>

<!-- Finally, the tcp and udp elements define connections that use the TCP -->
<!-- or UDP protocols.  They contain source and dest elements to define    --> 
<!-- which ports the connections use.  If no source child is present, then -->
<!-- any port may be the source, and if no dest child is present, any port -->
<!-- may be the destination. -->
<!ELEMENT tcp (source | dest | description | pragma)* >
<!ATTLIST tcp
    source (client | server) "client"
    dest   (client | server) "server">

<!ELEMENT udp (source | dest | description | pragma)* >
<!ATTLIST udp
    source (client | server) "client"
    dest   (client | server) "server"
    direction (both) #IMPLIED>
	      
<!ELEMENT source (port | portrange)* >
<!ATTLIST source>

<!ELEMENT dest (port | portrange)* >
<!ATTLIST dest>

<!-- A port's portnum attribute can be	-->
<!-- * an integer in 0..65535;		-->
<!-- * "any": any port is allowed;	-->
<!-- * "privileged": any port in 0..1023 (typically used by privileged -->
<!--   server processes); -->
<!-- * "non-privileged": any port in 1024..65535; -->
<!-- * "dynamic": a port in 1024..65535, dynamically assigned to a client -->
<!--   process. -->
<!-- The stance attribute is ignored. -->
<!ELEMENT port EMPTY>
<!ATTLIST port
    portnum CDATA       #REQUIRED
    stance  (alternate) #IMPLIED>

<!-- A portrange's start and end attributes are integers in 0..65535, with -->
<!-- start <= end. -->
<!ELEMENT portrange EMPTY>
<!ATTLIST portrange
    start   CDATA       #REQUIRED
    end     CDATA       #REQUIRED
    stance  (alternate) #IMPLIED>

=== SamAxe/guard-puppy/protocoldb/networkprotocoldb.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE protocoldb
    PUBLIC "-//Simonzone//DTD protocoldb 1.0//EN"
    "http://www.simonzone.com/software/protocoldb/1.0/protocoldb.dtd">
<!-- Network Protocol database                          -->
<!-- Published under the GNU GPL                        -->
<!-- http://www.simonzone.com/software/guarddog/        -->
<!--                                                    -->
<!-- Author:                                            -->
<!--   Simon Edwards, simon@simonzone.com               -->
<!--   Maciej Plewa, (contrib)                          -->
<!--   Jarl Stefansson,  (contrib)                      -->
<!--   Martin Ostertag (contrib)                        -->
<!--   Glen Ditchfield (DTD, XML validation)            -->
<!--   Steve Horsley (contrib)                          -->
<!--   Roger Luethi (contrib)                           -->
<!--   Vassilis Virvilis (contrib)                      -->
<!--                                                    -->
<!-- Translation:                                       -->
<!--   DE -  Stephan Johach, lucardus@onlinehome.de     -->
<!--         Ralf Hempel, Dominik Stadler               -->
<!--   NL -  Rinse de Vries, rinse@kde.nl               -->
<!--   FR -  Pascal Billery Schneider                   -->
<!--   IT -  Ceoldo Costantino, inverness1ATvirgilio.it -->
<!--   ES -  Antonio Diaz Cayuela                       -->
<!--                                                    -->
<!-- Last Modified: 26/11/2006                          -->
<!--                                                    -->
<protocoldb lines="3305">
<protocol name="FTP">
  <longname>FTP - File Transfer Protocol</longname>
  <longname lang="de">FTP - File Transfer Protocol</longname>
  <longname lang="nl">FTP - File Transfer Protocol</longname>
  <longname lang="fr">FTP - Protocole de transfert de fichier</longname>
  <longname lang="it">FTP - Protocollo di trasferimento file</longname>
  <longname lang="es">FTP - Protocolo de transferencia de ficheros</longname>
  <description>Very common protocol used to transfer files  on one computer to
  or from another computer across the network.</description>
  <description lang="de">Verbreitetes Protokoll zur Übertragung von Dateien zwischen
  Rechnern in einem Netzwerk.</description>
  <description lang="nl">Zeer verbreid protocol dat wordt gebruikt voor
  bestandsoverdrachten tussen twee computers over een netwerk</description>
  <description lang="fr">Protocole extrêmement usuel pour transférer par le réseau
  des fichiers d'un ordinateur vers (ou depuis) un autre ordinateur.</description>
  <description lang="it">Protocollo molto comune usato per trasferire file da un computer
  ad un altro, attraverso una rete.</description>
  <description lang="es">Protocolo muy común usado para transferir ficheros de un ordenador 
  a otro a través de una red.</description>
  <classification class="File"/>
  <pragma name="guarddog">ip_conntrack_ftp</pragma>
  <network>
    <tcp source="client" dest="server">
      <description>Control connection</description>
      <description lang="de">Steuerungsverbindung</description>
      <description lang="nl">Sturingsverbinding</description>
      <description lang="fr">Connexion de contrôle</description>
      <description lang="it">Controllo connessione</description>
      <description lang="es">Conexión de control</description>
      <source><port portnum="dynamic"/></source>
      <dest><port portnum="21"/></dest>
    </tcp>
    <tcp source="server" dest="client">
      <description>Data connection</description>
      <description lang="de">Datenverbindung</description>
      <description lang="nl">Dataverbinding</description>
      <description lang="fr">Connexion de données</description>
      <description lang="it">Connessione dati</description>
      <description lang="es">Conexión de datos</description>
      <source><port portnum="20"/></source>
      <dest><port portnum="nonprivileged"/></dest>
      <pragma name="guarddog">RELATED</pragma>
    </tcp>
    <tcp source="client" dest="server">
      <description>Data connection passive mode</description>
      <description lang="de">Datenverbindung passiver Modus</description>
      <description lang="nl">Dataverbinding passieve modus</description>
      <description lang="fr">Connexion de données en mode passif</description>
      <description lang="it">Modo passivo della connessione dati</description>
      <description lang="es">Conexión de datos en Modo Pasivo</description>
      <source><port portnum="nonprivileged"/></source>
      <dest><port portnum="nonprivileged"/></dest>
      <pragma name="guarddog">RELATED</pragma>
    </tcp>
  </network>
  <security threat="medium" falsepos="low"/>
  <reference href="http://www.robertgraham.com/pubs/firewall-seen.html">
  FAQ: Firewall Forensics (What am I seeing?)</reference>
</protocol>

<protocol name="SSH">
  <longname>SSH - Remote Login Protocol</longname>
  <longname lang="de">SSH - Protokoll für die Anmeldung auf einer entfernten Maschine</longname>
  <longname lang="nl">SSH - protocol voor het inloggen op computers op afstand</longname>
  <longname lang="fr">SSH - Ouvrir une session sur une machine distante</longname>
  <longname lang="it">SSH - Protocollo di accesso remoto</longname>
  <longname lang="es">SSH - Protocolo de acceso remoto</longname>
  <description>Secure SHell protocol is used to log into and execute commands
  on a remote computer.  It is provides encrypted communications and is
  intended for use accross an insecure network. It replaces the older insecure
  rlogin, rsh and telnet protocols.</description>
  <description lang="de">Das Secure SHell Protokoll wird zum Anmelden und Ausführen von
  Befehlen auf entfernten Rechnern verwendet. Es bietet verschlüsselte Kommunikation
  und ist für die Anwendung in unsicheren Netzwerken gedacht. Es ersetzt die älteren und
  unsicheren Protokolle rlogin, rsh und telnet.</description>
  <description lang="nl">Het Secure SHell-protocol wordt gebruikt voor het inloggen op 
  een computer op afstand en het uitvoeren van commando's op deze externe computer.
  Het levert versleutelde communicaties en is bedoeld voor gebruik op 
  onveilige netwerkverbindingen. Het is de vervanger voor het oudere en minder veilige
  rlogin, rsh en telnet.</description>
  <description lang="fr">Le protocole Secure SHell permet d'ouvrir une session
  interactive sur une machine distante afin d'envoyer des commandes ou des fichiers de
  façon sécurisée. Les communications sont chiffrées, ce qui permet son utilisation à
  travers un réseau peu sûr. Il remplace les anciens protocoles non-sécurisés rlogin,
  rsh et telnet.</description>
  <description lang="it">Il Secure SHell Protocol è usato per connettersi ed eseguire comandi su   
  un computer remoto: questo protocollo provvede comunicazioni cifrate ed è inteso per l'uso su 
  una rete non sicura. Rimpiazza i più vecchi (ed insicuri) protocolli  rlogin, rsh e telnet.</description>
  <description lang="es">El protocolo Secure SHell es usado para conectarse remotamente a un ordenador y darle
  órdenes: ofrece comunicación cifrada y está concebido para su uso sobre una red insegura. Reemplaza
  a los viejos e inseguros protocolos rlogin, rsh y telnet.</description>
  <classification class="Session"/>
  <network>
    <tcp>
  	  <description>Normal connection</description>
	  <description lang="de">Normale Verbindung</description>
	  <description lang="nl">Normale verbindingen</description>
	  <description lang="fr">Connexion Normale</description>
	  <description lang="it">Connessione normale</description>
	  <description lang="es">Conexión normal</description>
      <source><port portnum="dynamic"/></source>
      <dest><port portnum="22"/></dest>
    </tcp>
    <tcp>
  	  <description>privileged source port (rhosts compat.)</description>
	  <description lang="de">Privilegierter Quellport (rhosts compat.)</description>
	  <description lang="nl">Bronpoort met privileges (rhosts compatible.)</description>
	  <description lang="fr">Port source privilégié (compat. rhosts)</description>
	  <description lang="it">Porta sorgente privilegiata (rhosts compatibile.)</description>
	  <description lang="es">Puerto de origen privilegiado (compatibilidad rhosts)</description>
      <source><port portnum="privileged"/></source>
      <dest><port portnum="22"/></dest>
    </tcp>
  </network>
  <security threat="medium" falsepos="medium"/>
  <reference href="http://www.robertgraham.com/pubs/firewall-seen.html">
  FAQ: Firewall Forensics (What am I seeing?)</reference>
</protocol>

<protocol name="Telnet">
  <longname>Telnet</longname>
  <longname lang="de">Telnet</longname>
  <longname lang="nl">Telnet</longname>
  <longname lang="fr">Telnet</longname>
  <longname lang="it">Telnet</longname>
  <longname lang="es">Telnet</longname>
  <description>Telnet is used to log into and execute commands on a remote
  computer.  It is vulnerable to 'sniffing' or 'snooping' and is not
  considered secure. Secure Shell (SSH) is the secure successor to telnet.</description>
  <description lang="de">Telnet wird zum Anmelden und Ausführen von
  Befehlen auf entfernten Rechnern verwendet. Es ist anfällig für "sniffing" und "snooping"
  und wird als unsicher betrachtet. Secure Shell (SSH) ist der sichere Nachfolger
  von Telnet. </description>
  <description lang="nl">Telnet wordt gebruikt voor het inloggen op een
  computer op afstand en het uitvoeren van commando's op deze externe computer.
  Telnet is kwetsbaar voor 'sniffing' of 'snooping' en wordt zeker niet als veilig beschouwd.
  Secure SHell (SSH) is de beter beveiligde opvolger van telnet.
    </description>
  <description lang="fr">Telnet permet d'ouvrir une session et d'envoyer des commandes sur
  un ordinateur distant. Parce que les données circulent en clair, il est vulnérable tant au
